### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Spontini** [lucko/tapir#4]
Hello, Itried usingthis plugin but i don't understand where the functions come from.
  ```source.gameMode().set(GameModes.CREATIVE); ```
 Like this, when i look at sponge api, there are getGameMode() function but it doesn't work. Instead of that i can use 
 ```source.gameMode().get() ```

Where can i find the docs for this plugin?

**Comment by lucko** [comment]
Sponge JavaDocs are available from their site.

There are limited docs available for tapir - the readme has some example code though.

**Comment by lucko** [comment]
Oh, looks like I started writing a brief tutorial here too :)

https://github.com/lucko/tapir/wiki

**Comment by Spontini** [comment]
Thanks, can't wait for the wiki!
