### ISSUE TITLE
Evaluating if a sender is a player

### ISSUE THREAD

**Issue by Column01** [lucko/tapir#5]
How would one evaluate if a command sender is a player? Using `Player.class` in an `instanceof` does not bode well.

`source instanceof Player.class` Gives this error:

![img](https://i.imgur.com/pruUKdp.png)

**Comment by Column01** [comment]
Would specifying the full classpath help? I.E. `org.spongepowered.api.entity.living.player.Player.class`?
or by importing said class using a similar method you described here: #2

**Comment by Column01** [comment]
`var player = Java.type("org.spongepowered.api.entity.living.player.Player")` then using `source instanceof player` worked.

**Comment by Column01** [comment]
Just a poke also, maybe it would help if the docs were more fleshed out (wink wink nudge nudge)

**Comment by lucko** [comment]
Sorry, I haven't got time to write more documentation at the moment - I will gladly accept any contributions though.

**Comment by lucko** [comment]
I've made the wiki on this repo publicly editable :)
